[CmdletBinding()]
param(
    [int]$Port = 8001,
    [switch]$SkipInstall
)

$ErrorActionPreference = 'Stop'
$repoRoot = Split-Path -Parent $PSScriptRoot
$venvPython = Join-Path $repoRoot '.venv\Scripts\python.exe'
$requirements = Join-Path $repoRoot 'requirements.txt'
$envFile = Join-Path $repoRoot '.env'

Set-Location $repoRoot

if (-not (Test-Path -LiteralPath $venvPython)) {
    $launcher = Get-Command py -ErrorAction SilentlyContinue
    if (-not $launcher) {
        throw 'Python was not found. Install Python 3.11 or newer first.'
    }
    & $launcher.Source -3 -m venv (Join-Path $repoRoot '.venv')
}

if (-not (Test-Path -LiteralPath $envFile)) {
    $passwordBytes = New-Object byte[] 24
    $rng = [Security.Cryptography.RandomNumberGenerator]::Create()
    try {
        $rng.GetBytes($passwordBytes)
    } finally {
        $rng.Dispose()
    }
    $password = ([BitConverter]::ToString($passwordBytes) -replace '-', '').ToLowerInvariant()
    @(
        '# Generated by scripts/dev.ps1. Do not commit this file.'
        "DASHBOARD_PASSWORD=$password"
        "PORT=$Port"
    ) | Set-Content -LiteralPath $envFile -Encoding utf8
    Write-Host "Created local .env. Login password: $password" -ForegroundColor Yellow
}

if (-not $SkipInstall) {
    & $venvPython -m pip install --disable-pip-version-check -r $requirements
}

$env:PORT = [string]$Port
$env:PRISM_DATA_DIR = Join-Path $repoRoot '.dev-data'
$env:PRISM_INBOX_DIR = Join-Path $env:PRISM_DATA_DIR 'inbox'
Write-Host "Starting Prism at http://127.0.0.1:$Port" -ForegroundColor Green
& $venvPython server.py
